### ISSUE TITLE
Placeholder handling in q_genrelax/q_genfeps

### ISSUE THREAD

**Issue by acmnpv** [mpurg/qtools#1]
Currently, q_genrelax and q_genfeps both will replace place-holders found in procedure files with the numbers found in the provided PDB files.
This does not happen if the scripts are provided with q_makefep generated FEP files that also contain the place-holders. There, the files first have to passed through q_pdbindex to replace the numbers.

A feature request for genrelax/genfeps is the automatic detection of place-holders in the initial FEP file passed to either script, and replacement with PDB atom numbers from a provided PDB file.

**Comment by mpurg** [comment]
Added, see if it works.
