### ISSUE TITLE
Option to test with system compiled Q

### ISSUE THREAD

**Issue by malramsay64** [mpurg/qtools#18]
It would be nice to have an option to test qtools with the Q binary in PATH, meaning the Q executable running the tests is the Q executable running the production code.

I attempted this by removing the download code and setting the `QBIN_DIR` variable producing the error (see [this PR](https://github.com/malramsay64/qtools/pull/1/files) for changes):

``` 
####################################################
|  Testing:    q_automapper/1-probrcl/
####################################################
Working in /tmp/QTOOLS_TESTS_2Tk/1-probrcl_P4Z
Checking '*log'
sed: can't read *log: No such file or directory
FAIL  Check the following files:
/tmp/QTOOLS_TESTS_2Tk/1-probrcl_P4Z/diffs.txt
/tmp/QTOOLS_TESTS_2Tk/1-probrcl_P4Z/stdout.txt
```

**Comment by mpurg** [comment]
Will look at this.
It probably failed due to the variable being assigned a relative rather than absolute path.

**Comment by mpurg** [comment]
Solved in devel.
