### ISSUE TITLE
q_genfeps.py: is parsing comments

### ISSUE THREAD

**Issue by amrein** [mpurg/qtools#2]
Command:
 q_genfeps.py genfeps_10ps-f.proc 9_dyn_eq_publication.inp relax --fromlambda 0.5 

Observed:
ERROR: Found placeholders in proc. file, but no PDB was given: $RESID.ATOMNAME$, $315.P1$, $316.H2$

Expected:
All Placeholders are commented out (# at the start of the line). Hence q_genfeps.py should not see/parse/complain about them.

Suggested Fix:
Strip off everything after a '#', before parsing.

**Comment by mpurg** [comment]
Thanks for pointing it out. It was a known issue for a while, I just always decided to remove the comments instead...

Fixed now
