### ISSUE TITLE
Mention status of python3

### ISSUE THREAD

**Issue by malramsay64** [mpurg/qtools#7]
To be clear, I have no problem with this currently being python2 only, although I feel there should be some mention of the current status of python 3 and whether you intend to support it. Particularly seeing the next version of Red Hat Enterprise Linux 8, [python2 will be replaced with python3](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/chap-red_hat_enterprise_linux-7.5_release_notes-deprecated_functionality).

**Comment by malramsay64** [comment]
Something like; Python 3 is unsorted at this time and will be re-evaluated when RHEL 8 is released.

**Comment by mpurg** [comment]
Support for Python 3.x has been on my to do list for a long time actually. 
Thanks for bringing it up, especially the RHEL8 thing, I was not aware of that.
I'm taking this opportunity to port the code.

**Comment by mpurg** [comment]
Ok, ported and tested. (devel branch)
